In [ ]:
from raphtory import Graph
import numpy as np

# Identify all unique nodes
#print(list(g.vertices.name))
# [ms3123,ms323,...]

# Create a node index map
node_index = {node_name: i for i, node_name in enumerate(list(g.vertices.name))}
#print(node_index)
# [ms3123:0, ms323:1,...]

# Initialise adjacency matrix
adjacency_matrix = np.zeros((len(list(g.vertices.name)), len(list(g.vertices.name))), dtype=int)
#[[0 0 0 ... 0 0 0]
# [0 0 0 ... 0 0 0]
# [0 0 0 ... 0 0 0]
# ...
# [0 0 0 ... 0 0 0]
# [0 0 0 ... 0 0 0]
# [0 0 0 ... 0 0 0]]


# Populate adjacency matrix
for edge in g.edges:
    src_index = node_index[edge.src.name]
    dst_index = node_index[edge.dst.name]

    adjacency_matrix[src_index, dst_index] = 1

#print(adjacency_matrix)
#[[0 1 0 ... 0 0 0]
# [0 0 0 ... 0 0 0]
# [0 0 1 ... 0 0 0]
# ...
# [0 0 0 ... 0 0 0]
# [0 0 0 ... 0 0 0]
# [0 0 0 ... 0 0 0]]

A_dict = {'1': adjacency_matrix}
print(A_dict)

# Pickle the variables